name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 16

      # - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      #   with:
      #     node-version: 20
      #     cache: npm

      - name: safe-chain setup
        run: |
          npm i -g @aikidosec/safe-chain
          safe-chain setup-ci --include-python
